LOCAL_PATH := $(call my-dir)

# Plumpy icon overlays (Jairo Edition)
# Extraidos do Iconify v7.3.0 - aplicados nativamente na ROM

include $(CLEAR_VARS)
LOCAL_MODULE := IconifyComponentIPSUI4
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := IconifyComponentIPSUI4.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_OVERRIDES_PACKAGES :=
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := IconifyComponentAMGC
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := IconifyComponentAMGC.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := IconifyComponentIPAS4
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := IconifyComponentIPAS4.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
include $(BUILD_PREBUILT)